name: Greetings

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Greet new contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            🎉 **Thank you for your issue!** We appreciate your contribution to our project. One of our team members will review your issue shortly.
          pr-message: >
            🚀 **Thank you for your pull request!** Your efforts to improve our project are much appreciated. Our team will review your PR soon.

      - name: Notify via Slack
        if: always()
        uses: 8398a7/action-slack@v4
        with:
          status: ${{ job.status }}
          fields: workflow,job,commit,repo,ref,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
